// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwkgxylqvzrsinzroeif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3a2d4eWxxdnpyc2luenJvZWlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MDQzMzAsImV4cCI6MjA2NTk4MDMzMH0.ns07b2wbeZUjvKH5es3N87hHV934krUoTxChkglS01c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);